### ISSUE TITLE
action icon

### ISSUE THREAD

**Issue by caarlos0** [charmbracelet/vhs-action#11]
could we use our icon instead of the default orange play one?

https://github.com/marketplace/actions/vhs-action

**Comment by aymanbagabas** [comment]
GitHub Actions can't have their own icons, but they can be [customized](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding). I've added this branding 
![image](https://user-images.githubusercontent.com/3187948/199065996-44001a49-0319-4378-ab25-ffabd30505e1.png)
