### ISSUE TITLE
Flag to only install VHS, without running it

### ISSUE THREAD

**Issue by taminomara** [charmbracelet/vhs-action#145]
Hey! I'm building VHS integrations for pytest and python-sphinx, and it\d be helpful to have an action that only installs VHS (because integration will do all the running).

Right now I have to [put a fake tape into my repo](https://github.com/taminomara/sphinx-vhs/blob/bc62e34a1342801d1bba5f74510654cc85cb4af4/.github/workflows/docs.yaml#L32-L37).

Relevant link: #56.

**Comment by aymanbagabas** [comment]
Hi @taminomara, as of v1.2.1, VHS will get installed on the runner's path and the tape path is no longer required.

**Comment by taminomara** [comment]
It is true. However, the VHS action will fail before installing anything if there is no tape file for it to execute. This means that I have to put an empty tape file in my repo, which I'd prefer to avoid.

**Comment by taminomara** [comment]
I'd like to have a mode in which VHS action does not check or run tape at all. Please, reopen this.
