### ISSUE TITLE
provide `v1` tag

### ISSUE THREAD

**Issue by mxcl** [charmbracelet/vhs-action#28]
it's the standard for actions, and means users can pin to `v1` (it needs to be updated each release).

we automate this: https://github.com/teaxyz/setup/blob/main/.github/workflows/vx-tagger.yml

**Comment by aymanbagabas** [comment]
Hi @mxcl!

There is a `v1` [tag](https://github.com/charmbracelet/vhs-action/tree/v1) already, you can do `uses: charmbracelet/vhs-action@v1` in your workflow.
Release tags are not automated yet, and it's something I've been looking into adding. Thanks for sharing!

**Comment by mxcl** [comment]
Oh sorry. I looked and didn’t see it.
