### ISSUE TITLE
Lipgloss styling not applied in the generated gif

### ISSUE THREAD

**Issue by Morphclue** [charmbracelet/vhs-action#91]
# Description
In my Bubble Tea application, I have implemented a user interface using the lipgloss package for styling. The application runs as expected when executed locally, with the desired lipgloss styles being applied. However, when running the application through the `charmbracelet/vhs-action` GitHub Action to generate a GIF, the lipgloss styles are not visible in the resulting `.gif`.

I don't have the expertise in Go / Linux to be precise / pinpoint the problem, but my suggestions would be that:
- vhs-action currently doesn't support lipgloss colors
- my action-env isn't set up correctly (colors missing in the default ubuntu-latest env?)

I have tried to add `xterm-256color` to the [workflow](https://github.com/Morphclue/ygo-bubble-tea/blob/master/.github/workflows/vhs.yml), but it still did not display the correct colors.
Also ignore the installation at the beginning. I have tried to incorporate golang-cache into my action, and thanks to the new version of Lipgloss, something has been downloaded again during the new generation of a tape.

### Versions
* vhs-action v1
* lipgloss latest (0.7.1)

### References
- [My repo](https://github.com/Morphclue/ygo-bubble-tea)
- ![Demo Usage](https://github.com/Morphclue/ygo-bubble-tea/blob/master/assets/demo.gif?raw=true)

**Comment by bashbunni** [comment]
When termenv tries to query the terminal used in CI, it might lock up the CI process. Circle CI, for example. This was a fix to resolve that issue. In this case we know the environment this is being run in, so we can unset the env variable we're setting in termenv to prevent the colours from showing. 

Ayman is going to work on this :)

**Comment by aymanbagabas** [comment]
@Morphclue could you try using the `ci-colors` branch in your workflow?

The config should be like this
```yaml
      - uses: charmbracelet/vhs-action@ci-colors
        with:
          path: 'demo.tape'
        env:
          TERM: xterm-256color
```

**Comment by Morphclue** [comment]
Thank you very much for the help.
The problem seems to be fixed. In any case, the colors are now displayed correctly. 

I don't know if this is related to the change in the `ci-colors`-branch, but the "load times" until the program is executed after a `go run .` seem to be longer than before. But this could also be due to my project. I would leave it to you to decide if this is relevant to this issue or if you want to close this issue.
